### ISSUE TITLE
Differences with Symfony's PropertyAccess?

### ISSUE THREAD

**Issue by mnapoli** [peridot-php/object-path#1]
Hi, I'm curious to learn if there are differences with [Symfony's PropertyAccess](http://symfony.com/doc/current/components/property_access/introduction.html) component?

**Comment by brianium** [comment]
Ah. I was not aware of the PropertyAccess component :)

They seem nearly identical. The only difference I can see is that `object-path` uses the the familiar `->` operator for property access instead of `.`

Perhaps [Leo](https://github.com/peridot-php/leo) should use the PropertyAccess component. I'm generally a fan of Symfony components, so I will definitely investigate.

Thanks!

**Comment by mnapoli** [comment]
OK thanks for clarifying, I wasn't sure. By the way I'm looking into Peridot and it looks really great! Congrats

**Comment by brianium** [comment]
Thank you for the kind words!
